#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <math.h>

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define FPS 30
#define FRAME_TARGET_TIME (1000 / FPS)

#define GRID_COLUMNS 10
#define GRID_SPACE_SIZE 30
#define GRID_MAX_ITEMS 255

#define PLAYER_WIDTH 0.75 * GRID_SPACE_SIZE
#define PLAYER_HEIGHT PLAYER_WIDTH

#define BORDER_LEFT (WINDOW_WIDTH / 2) - (0.5 * GRID_COLUMNS * GRID_SPACE_SIZE)
#define BORDER_RIGHT (WINDOW_WIDTH / 2) + (0.5 * GRID_COLUMNS * GRID_SPACE_SIZE)

#define GRID_ROWS (WINDOW_HEIGHT / GRID_SPACE_SIZE)

#endif
